/*
 This configuration ensures that all log topics are right-padded with spaces to align uniformly on the screen.
 The padding facilitates easy reading and monitoring by ensuring that all messages end at the same column,
 which helps in quickly scanning the log output visually and maintaining a tidy and consistent format on the logger server.
*/
module.exports = {
    START:                                    "○ start                                    ",
    STOP:                                     "○ stop                                     ",
    INFO:                                     "○ info                                     ",
    ARCHIVE_SYNCRONIZATION_FINISHED:          "✓ archive_syncronization_finished          ",
    RECEIVED_DRAIN_EVENT:                     "✓ received_drain_event                     ",
    ALL_BATCHES_SENT:                         "✓ all_batches_sent                         ",
    BLACKLIST_FILTERING_LOOP_DONE:            "✓ blacklist_filtering_loop_done            ",
    ADD_USER_TO_BLACKLIST:                    "x add_user_to_blacklist                    ",
    REMOVE_USER_FROM_BLACKLIST:               "✓ remove_user_from_blacklist               ",
    NON_BLACKLIST_USERS_COUNT:                "○ non_blacklist_users_count                ",
    TOTAL_STORED_USERS:                       "○ total_stored_users                       ",
    NEW_BLOCK_RECEIVED:                       "✓ new_block_received                       ",
    LATEST_STORED_BLOCK:                      "○ latest_stored_block                      ",
    ARCHIVE_USERS_GROUP:                      "○ archive_users_group                      ",
    USERS_SAVED_TO_ARCHIVE:                   "✓ users_saved_to_archive                   ",
    USER_SKIPPED_BY_LOW_HF:                   "x user_skipped_by_low_hf                   ",
    USER_SKIPPED_BY_HIGH_HF:                  "x user_skipped_by_high_hf                  ",
    USER_SKIPPED_BY_HF:                       "x user_skipped_by_hf                       ",
    USERS_SKIPPED_BY_TO_DIFFERENT_HF:         "x users_skipped_by_to_different_hf         ",
    USER_SKIPPED_BY_LOW_COLLATERAL:           "x user_skipped_by_collateral               ",
    ADD_TO_BLACKLIST_BY_LOW_COLLATERAL:       "x add_to_blacklist_by_low_collateral       ",
    ADD_TO_BLACKLIST_BY_LOW_BORROW:           "x add_to_blacklist_by_low_borrow           ",
    ADD_TO_BLACKLIST_BY_LOW_HF:               "x add_to_blacklist_by_low_hf               ",                
    ADD_TO_BLACKLIST_BY_HIGH_HF:              "x add_to_blacklist_by_high_hf              ",           
    USER_SKIPPED_BY_LOW_BORROW:               "x user_skipped_by_low_borrow               ",
    USER_ACCEPTED_BY_HF_AFTER_SIML_RESULT:    "✓ user_accepted_by_hf_after_siml_result    ",
    USER_SKIPPED_BY_FILTERS:                  "x user_skipped_by_filters                  ",
    USERS_SKIPPED_BY_FILTERS:                 "x users_skipped_by_filters                 ",
    USER_ACCEPTED:                            "✓ user_accepted                            ",
    USER_SKIPPED:                             "x user_skipped                             ",               
    BORROW_SKIPPED:                           "x borrow_skipped                           ",
    COLLATERAL_SKIPPED:                       "x collateral_skipped                       ",
    BORROW_AND_COLLATERAL_SKIPPED:            "x borrow_and_collateral_skipped            ",
    BORROW_AND_COLLATERAL_ACCEPTED:           "✓ borrow_and_collateral_accepted           ",           
    SIMULATION_PASSED_WITH_STATUS_SUCCESS:    "✓ simulation_passed_with_status_success    ",
    SIMULATION_PASSED_WITH_STATUS_FAILED:     "x simulation_passed_with_status_failed     ",
    SIMULATION_SUCCESS:                       "○ simulation_success                       ",
    SIMULATION_ERROR:                         "E simulation_error                         ",
    PROVIDER_ERROR:                           "E provider_error                           ",
    USERS_FROM_REDIS_TO_SIMULATION_BY_ASSEST: "○ users_from_redis_to_simulation_by_asset  ",
    ALL_UNIQUE_USERS_FROM_REDIS_TO_SIMULATION:"○ all_unique_users_from_redis_to_simulation",
    NUMBER_OF_USERS_TO_SIMULATION:            "✓ number_of_users_to_simulation            ",
    NO_USERS_FROM_REDIS_BY_ASSEST:            "x no_users_from_redis_by_asset             ",
    NO_USERS_FROM_REDIS_TO_SIMULATION:        "x no_users_from_redis_to_simulation        ",
    ALL_BATCH_OF_USERS_SKIPPED_BY_HF:         "x all_batch_of_users_skipped_by_hf         ",
    LIQUIDATE_EVENT:                          "✓ liquidate_event                          ",
    SIMULATIONS_STARTED:                      "✓ simulations_started                      ",
    INPUT_TRANSMIT:                           "○ input_transmit                           ",
    ERROR_MESSAGE:                            "E error_message                            ",
    RECIEVED_INPUT_ADDRESS:                   "✓ recieved_input_address                   ",
    SEND_USER_TO_DATA_FETCHER:                "✓ send_user_to_data_fetcher                ",
    SEND_DRAIN_EVENT:                         "✓ send_drain_event                         ",
    ERROR_MESSAGE_IN_QUEUE:                   "E error_message_in_queue                   ",
}
